// <auto-generated />
using System;
using MediiProgProiect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediiProgProiect.Migrations
{
    [DbContext(typeof(MediiProgProiectContext))]
    [Migration("20240218170058_TipMasina")]
    partial class TipMasina
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MediiProgProiect.Models.MasinaC", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("DataFabricarii")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("VanzatorID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("VanzatorID");

                    b.ToTable("MasinaC");
                });

            modelBuilder.Entity("MediiProgProiect.Models.Tip", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NumeTip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Tip");
                });

            modelBuilder.Entity("MediiProgProiect.Models.TipMasina", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("MasinaCID")
                        .HasColumnType("int");

                    b.Property<int>("MasinaID")
                        .HasColumnType("int");

                    b.Property<int>("TipID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MasinaCID");

                    b.HasIndex("TipID");

                    b.ToTable("TipMasina");
                });

            modelBuilder.Entity("MediiProgProiect.Models.Vanzator", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NumeVanzator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Vanzator");
                });

            modelBuilder.Entity("MediiProgProiect.Models.MasinaC", b =>
                {
                    b.HasOne("MediiProgProiect.Models.Vanzator", "Vanzator")
                        .WithMany("MasiniC")
                        .HasForeignKey("VanzatorID");

                    b.Navigation("Vanzator");
                });

            modelBuilder.Entity("MediiProgProiect.Models.TipMasina", b =>
                {
                    b.HasOne("MediiProgProiect.Models.MasinaC", "MasinaC")
                        .WithMany("TipMasini")
                        .HasForeignKey("MasinaCID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediiProgProiect.Models.Tip", "Tip")
                        .WithMany("TipMasini")
                        .HasForeignKey("TipID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasinaC");

                    b.Navigation("Tip");
                });

            modelBuilder.Entity("MediiProgProiect.Models.MasinaC", b =>
                {
                    b.Navigation("TipMasini");
                });

            modelBuilder.Entity("MediiProgProiect.Models.Tip", b =>
                {
                    b.Navigation("TipMasini");
                });

            modelBuilder.Entity("MediiProgProiect.Models.Vanzator", b =>
                {
                    b.Navigation("MasiniC");
                });
#pragma warning restore 612, 618
        }
    }
}
